### ISSUE TITLE
uart例程，MDK 采用AC6 无法打印输出

### ISSUE THREAD

**Issue by DaLaoHei1986** [ArteryTek/AT32F421_Firmware_Library#1]
采用 printf 无法打印输出，ARM Compiler version 6（AC6）版本为V6.15

**Comment by DaLaoHei1986** [comment]
debug 直接卡死在   while(usart_flag_get(PRINT_UART, USART_TDBE_FLAG) == RESET);

**Comment by DaLaoHei1986** [comment]
> 采用 printf 无法打印输出，ARM Compiler version 6（AC6）版本为V6.15

debug 发现 是直接卡死在while(usart_flag_get(PRINT_UART, USART_TDBE_FLAG) == RESET);  感觉库函数做的不是很完善？

**Comment by ArteryTek** [comment]
抱歉，迟到的回复。
这个现象确实在compiler v6.15上有复现，具体原因更倾向于是编译器版本差异导致，该版编译器在某些时刻会嵌入store  byte的指令，然而某些外设只能以word对齐访问。v6.16及v6.15以前的都ok
