### ISSUE TITLE
ADC header file has bits that are not documented

### ISSUE THREAD

**Issue by DualTachyon** [ArteryTek/AT32F421_Firmware_Library#2]
If you check in the header file below ADC register ctrl2 has 2 bits at [24] and [25],

https://github.com/ArteryTek/AT32F421_Firmware_Library/blob/master/libraries/drivers/inc/at32f421_adc.h#L264

However, the Reference Manual describes those bits as "reserved".

Reference Manual: www.arterychip.com/download/RM/RM_AT32F421_EN_V2.03.pdf

The reference manual specifies that OCTESEL is 3 bits long, so it is unclear what a 4th bit (octesel_h) would do.

**Comment by ArteryTek** [comment]
The reference manual is correct，BSP will fixed at next release version. 
Thanks for your feedback.
