### ISSUE TITLE
Incorrect register name for CRC "POLY"

### ISSUE THREAD

**Issue by DualTachyon** [ArteryTek/AT32F421_Firmware_Library#3]
Hi,

In the reference manual (RM_AT32F421_EN_V2.03.pdf), the POLY register is incorrectly named IDT. I confirmed that the library code seems correct. The header text for 10.3.5 is a copy of 10.3.4.

10.3.4 Initialization register (CRC_IDT)
Bit Register Reset value Type Description
Bit 31: 0 IDT 0xFFFF FFFF rw
Initialization data register
When CRC reset is triggered by the RST bit in the
CRC_CTRL register, the value in the initialization register
is written into the CRC_DT register as an initial value.

10.3.5 Initialization register (CRC_IDT)
Bit Register Reset value Type Description
Bit 31: 0 POLY 0x04C1 1DB7 rw
Polynomial coefficient
The generated polynomial is a divisor in CRC calculation.
Using CRC32 mode, this polynomial coefficient is
0x4C11DB7. Users can also set the polynomial coefficient
according to their needs.

**Comment by ArteryTek** [comment]
Thanks for your reply, we will fixed the issue at next version of the reference manul.
